# Generated by Django 3.0.4 on 2020-03-29 00:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0006_passwordresetcodes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='sahm',
        ),
        migrations.RemoveField(
            model_name='expense',
            name='user',
        ),
        migrations.AddField(
            model_name='expense',
            name='user',
            field=models.ManyToManyField(related_name='person2person', to='web.Person'),
        ),
        migrations.CreateModel(
            name='MadarKharj',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kharj', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='Kharj', to='web.Expense')),
                ('madarrrrr', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='Madar_Kharj', to='web.Person')),
            ],
        ),
    ]
