# Generated by Django 3.0.4 on 2020-04-01 19:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0010_remove_expense_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expense',
            name='madarrrrr',
        ),
        migrations.RemoveField(
            model_name='expense',
            name='member',
        ),
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manager', models.BooleanField(default=False)),
                ('expense', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.Expense')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.Person')),
            ],
        ),
    ]
