# Generated by Django 3.0.4 on 2020-04-01 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0012_membership_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='member',
            field=models.ManyToManyField(through='web.Membership', to='web.Person'),
        ),
    ]
