# Generated by Django 3.0.4 on 2020-04-02 23:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0015_manager'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='membership',
            name='manager',
        ),
    ]
