# Generated by Django 3.0.4 on 2020-04-15 16:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0018_manager'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='money',
        ),
    ]
